name: rate-tweets
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pandas
  - requests
  - numpy
  - pip:
    - otree>=2.1.28
    - service_identity
    - seaborn==0.9.0
    - matplotlib==3.1.2
